version: 2
updates:

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    labels:
      - dependencies
      - cicd
    commit-message:
      prefix: "chore: "
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    labels:
      - dependencies
      - cicd
    commit-message:
      prefix: "chore: "
